[pytest]
pythonpath = .
# Defines the directory where pytest should automatically search for tests.
testpaths = tests

# Defines the naming convention that pytest recognizes as valid tests.
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# Logging settings to display clear messages in the terminal during testing.
log_cli = true
log_cli_level = INFO