#Requires -Version 5.1
<#
.SYNOPSIS
    Installs the Aura BIM AI add-in into Autodesk Revit 2025.

.DESCRIPTION
    Copies the compiled Aura.Revit.dll and the Aura.addin manifest to the
    Revit 2025 Add-ins folder (%APPDATA%\Autodesk\Revit\Addins\2025\).
    The script must be run AFTER building the C# project in Visual Studio.

.NOTES
    Run from the Aura.Revit\ directory:
        powershell -ExecutionPolicy Bypass -File .\Install-AuraAddin.ps1

    To build first and then install in one go:
        dotnet build src\Aura.Revit.csproj -c Debug
        powershell -ExecutionPolicy Bypass -File .\Install-AuraAddin.ps1
#>

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ── Constants ──────────────────────────────────────────────────────────────────
$REVIT_VERSION    = "2025"
$ADDIN_NAME       = "Aura BIM AI"
$ADDINS_DIR       = Join-Path $env:APPDATA "Autodesk\Revit\Addins\$REVIT_VERSION"
$SCRIPT_DIR       = Split-Path -Parent $MyInvocation.MyCommand.Path

# Prefer Release over Debug if both exist; fall back to Debug for dev workflows.
$DLL_RELEASE = Join-Path $SCRIPT_DIR "src\bin\Release\net8.0-windows\Aura.Revit.dll"
$DLL_DEBUG   = Join-Path $SCRIPT_DIR "src\bin\Debug\net8.0-windows\Aura.Revit.dll"
$ADDIN_FILE  = Join-Path $SCRIPT_DIR "Aura.addin"

# ── Helper functions ───────────────────────────────────────────────────────────
function Write-Step { param([string]$Msg) Write-Host "  > $Msg" -ForegroundColor Cyan }
function Write-Ok   { param([string]$Msg) Write-Host "  [OK] $Msg" -ForegroundColor Green }
function Write-Warn { param([string]$Msg) Write-Host "  [WARN] $Msg" -ForegroundColor Yellow }
function Write-Fail { param([string]$Msg) Write-Host "  [FAIL] $Msg" -ForegroundColor Red }

# ── Banner ─────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "═══════════════════════════════════════════════" -ForegroundColor DarkCyan
Write-Host "   Aura BIM AI — Revit $REVIT_VERSION Add-in Installer  " -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════" -ForegroundColor DarkCyan
Write-Host ""

# ── Step 1: Make sure Revit is not running ─────────────────────────────────────
Write-Step "Checking that Revit is not running..."
$revitProcess = Get-Process -Name "Revit" -ErrorAction SilentlyContinue
if ($revitProcess) {
    Write-Fail "Revit is currently open. Please close Revit before installing the add-in."
    exit 1
}
Write-Ok "Revit is not running."

# ── Step 2: Locate the compiled DLL ───────────────────────────────────────────
Write-Step "Locating compiled Aura.Revit.dll..."

$dllSource = $null
if (Test-Path $DLL_RELEASE) {
    $dllSource = $DLL_RELEASE
    Write-Ok "Found Release build: $dllSource"
} elseif (Test-Path $DLL_DEBUG) {
    $dllSource = $DLL_DEBUG
    Write-Warn "Release build not found. Using Debug build: $dllSource"
} else {
    Write-Fail "DLL not found. Build the project first:"
    Write-Host "       dotnet build src\Aura.Revit.csproj -c Debug" -ForegroundColor Gray
    exit 1
}

# ── Step 3: Locate the .addin manifest ────────────────────────────────────────
Write-Step "Locating Aura.addin manifest..."
if (-not (Test-Path $ADDIN_FILE)) {
    Write-Fail "Aura.addin not found at: $ADDIN_FILE"
    exit 1
}
Write-Ok "Found: $ADDIN_FILE"

# ── Step 4: Create destination directory if needed ────────────────────────────
Write-Step "Ensuring target directory exists: $ADDINS_DIR"
if (-not (Test-Path $ADDINS_DIR)) {
    New-Item -ItemType Directory -Path $ADDINS_DIR -Force | Out-Null
    Write-Ok "Created: $ADDINS_DIR"
} else {
    Write-Ok "Directory exists."
}

# ── Step 5: Generate a deployment .addin with the absolute DLL path ───────────
# The manifest placed in the Addins folder must point to the DLL in the same folder,
# so we generate it dynamically rather than copying the source .addin as-is.
Write-Step "Generating deployment manifest..."
$targetDll  = Join-Path $ADDINS_DIR "Aura.Revit.dll"
$targetAddin = Join-Path $ADDINS_DIR "Aura.addin"

$addinContent = @"
<?xml version="1.0" encoding="utf-8"?>
<RevitAddIns>
  <AddIn Type="Application">
    <Name>Aura BIM AI</Name>
    <!-- Absolute path generated by Install-AuraAddin.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm') -->
    <Assembly>$targetDll</Assembly>
    <AddInId>8A1F8B5A-4B2E-4D89-9A0B-7D1C3E4F5A6B</AddInId>
    <FullClassName>Aura.Revit.App</FullClassName>
    <VendorId>AURA</VendorId>
    <VendorDescription>Aura Technologies - EcoBIM AI, www.aurabim.com</VendorDescription>
  </AddIn>
</RevitAddIns>
"@

Set-Content -Path $targetAddin -Value $addinContent -Encoding UTF8
Write-Ok "Manifest written to: $targetAddin"

# ── Step 6: Copy the DLL ──────────────────────────────────────────────────────
Write-Step "Copying Aura.Revit.dll..."
Copy-Item -Path $dllSource -Destination $targetDll -Force
Write-Ok "DLL copied to: $targetDll"

# Copy any additional dependency DLLs (everything except the Revit SDK assemblies,
# which are already present in the Revit installation).
$dllDir = Split-Path -Parent $dllSource
$deps = Get-ChildItem -Path $dllDir -Filter "*.dll" |
        Where-Object { $_.Name -ne "Aura.Revit.dll" -and $_.Name -notlike "Revit*.dll" }

foreach ($dep in $deps) {
    $destDep = Join-Path $ADDINS_DIR $dep.Name
    Copy-Item -Path $dep.FullName -Destination $destDep -Force
    Write-Ok "  Dependency: $($dep.Name)"
}

# ── Step 7: Copy the Web Dashboard ────────────────────────────────────────────
Write-Step "Copying the Web UI components..."
$webSource = Join-Path $SCRIPT_DIR "..\web"
$webDest = Join-Path $ADDINS_DIR "web"
if (Test-Path $webSource) {
    Copy-Item -Path $webSource -Destination $webDest -Recurse -Force
    Write-Ok "Web folder copied to: $webDest"
} else {
    Write-Warn "Web folder not found at: $webSource"
}

# ── Done ──────────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "═══════════════════════════════════════════════" -ForegroundColor DarkGreen
Write-Host "   Installation complete!" -ForegroundColor Green
Write-Host ""
Write-Host "   Next steps:" -ForegroundColor White
Write-Host "   1. Start the Aura Python API:" -ForegroundColor Gray
Write-Host "         cd EcoBIM-Logic-main" -ForegroundColor DarkGray
Write-Host "         python -m uvicorn api.main:app --reload --port 8000" -ForegroundColor DarkGray
Write-Host "   2. Open Revit 2025 with a model loaded." -ForegroundColor Gray
Write-Host "   3. Go to the 'Aura BIM' tab → click 'Aura Dashboard'." -ForegroundColor Gray
Write-Host "   4. Click 'Sync BIM Intelligence' to start the analysis." -ForegroundColor Gray
Write-Host "═══════════════════════════════════════════════" -ForegroundColor DarkGreen
Write-Host ""
